import type { Metadata } from "next";
import { Overpass, Syne, Cormorant } from "next/font/google";
import "./globals.css";

const overpass = Overpass({
  subsets: ["latin"],
  variable: "--overpass",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--syne",
  weight: ["400", "500", "600", "700", "800"],
});

const cormorant = Cormorant({
  subsets: ["latin"],
  variable: "--cormorant",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overpass.variable} ${syne.variable} ${cormorant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
